# Generated by Django 4.2.6 on 2023-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_alter_restaurants_cost_alter_restaurants_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='cost',
            field=models.CharField(max_length=4),
        ),
    ]
