# Generated by Django 4.2.6 on 2023-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_alter_restaurants_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='type3',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
